modLoader = "javafml"
loaderVersion = "[37,)"
license = "All rights reserved"
[[mods]]
modId = "glowinc"
version = "${file.jarVersion}"
displayName = "GlowInc"
authors = "J-Dill"
description = '''

'''
[[dependencies.glowinc]]
    modId = "forge"
    mandatory = true
    versionRange = "[37,)"
    ordering = "NONE"
    side = "BOTH"
[[dependencies.glowinc]]
    modId = "minecraft"
    mandatory = true
    versionRange = "[1.17,)"
    ordering = "NONE"
    side = "BOTH"
