modLoader = "javafml"
loaderVersion = "[40,)"
license = "MIT"
[[mods]]
modId = "glowinc"
version = "${file.jarVersion}"
displayName = "Glow Inc."
authors = "JDill"
description = '''
Glow Inc. is all about giving more uses to the glow ink sacs products by glow squids, along with providing other ink-related fun.
'''
[[dependencies.glowinc]]
    modId = "forge"
    mandatory = true
    versionRange = "[40,)"
    ordering = "NONE"
    side = "BOTH"
[[dependencies.glowinc]]
    modId = "minecraft"
    mandatory = true
    versionRange = "[1.18,)"
    ordering = "NONE"
    side = "BOTH"
